ajalt/mordant

.github/workflows/publish.yml
.github/workflows/test.yml

`gradle check` will cross compile linux binaries on all platforms. We can save time by only compiling the tests that can actually run.

Speed up native CI tests

---

mordant/src/commonMain/kotlin/com/github/ajalt/mordant/animation/Animation.kt

The `Animation` class itself and the `Terminal.textAnimation` function can be multiplatform, only `ProgressAnimation` depends on JVM only code.

Move Animation class to commonMain

---

mordant/build.gradle.kts
mordant/src/mingwX64Main/kotlin/com/github/ajalt/mordant/internal/tty.kt
mordant/src/nativeMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt
mordant/src/posixMain/kotlin/com/github/ajalt/mordant/internal/tty.kt

Implement reading passwords using [tcsetattr](https://pubs.opengroup.org/onlinepubs/009696799/functions/tcsetattr.html) on linux/macos. mingw is still unsupported

implement 'hideInput' on posix systems

---

CHANGELOG.md
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt

Check environment for stty location

---

mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalDetection.kt

They now both support hyperlinks
Kitty since 0.19.0 [2020-10-04]
https://sw.kovidgoyal.net/kitty/changelog/#id30
Alacritty since 0.11.0 [2022-10-13]
https://github.com/alacritty/alacritty/releases/tag/v0.11.0

Fix hyperlinks terminal detection for kitty + alacritty

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/rendering/OverflowWrap.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/rendering/Whitespace.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/widgets/Text.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/rendering/TextOverflowWrapTest.kt

#84 pointed out that the behavior was incorrect when combining OverflowWrap and Whitespace.wrap=false

Ignore OverflowWrap when Whitespace.wrap=false

---

README.md

with print and Markdown widget, because printMarkdown was removed in  47f0514a5a04e3cf79025b7deb035ea17e374b24.
I also took the liberty to replace File with Path, since the latter is generally recommended.

replace use of Terminal::printMarkdown in readme

---

mordant/build.gradle.kts
mordant/src/jvmMain/resources/META-INF/native-image/com/github/ajalt/mordant/jni-config.json
mordant/src/jvmMain/resources/META-INF/native-image/com/github/ajalt/mordant/proxy-config.json
mordant/src/jvmMain/resources/META-INF/native-image/com/github/ajalt/mordant/reflect-config.json
mordant/src/jvmMain/resources/META-INF/native-image/com/github/ajalt/mordant/resource-config.json

This PR adds GraalVM native image metadata to enable building Mordant and Clikt with native-image tool.
Fixes regression in Clikt 4 https://github.com/ajalt/clikt/issues/415 
The only thing I have no experience in is adding those resources into library JAR, so please fix if `java-library` approach is not the right one.

Add GraalVM native image metadata

---

.github/workflows/publish.yml

No need to do these jobs in forked repos, they will fail.

Disable publish jobs in forks

---

samples/table/build.gradle.kts

Previously, the "table.jar" generated for distribution was empty besides a "META-INF" directory. For background information see
https://youtrack.jetbrains.com/issue/KT-37964

Make the "table" sample work with the Gradle application plugin

---

mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalInfo.kt
samples/detection/README.md
samples/detection/build.gradle.kts
samples/detection/src/commonMain/kotlin/com/github/ajalt/mordant/samples/main.kt
settings.gradle.kts

Please have a look at the individual commit messages for the details.

Add a detection sample

---

mordant/src/commonMain/kotlin/com/github/ajalt/mordant/internal/HyperlinkIds.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/internal/MppH.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/widgets/Spinner.kt
mordant/src/jsMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt
mordant/src/nativeMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt
mordant/src/posixMain/kotlin/com/github/ajalt/mordant/internal/tty.kt

Kotlin 1.9.20 added some new restrictions on MPP code.

Add workarounds for new KMP warnings

---

docs/guide.md

A link to the issue will help with being able to follow the issue status, and viewing the workaround described in https://github.com/ajalt/mordant/issues/148

Docs: add link to 'multiplatform progressAnimation' issue

---

CHANGELOG.md
mordant/src/jsMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt

The existing JS implementation is referencing a node-only API for its shutdown hook.

Add browser-specific implementation of TerminalCursor

---

.github/workflows/build.yml
.github/workflows/release.yml
buildSrc/src/main/kotlin/mordant-publishing-conventions.gradle.kts
prepare_docs.sh

Add release workflow

---

mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/syscalls/nativeimage/SyscallHandler.nativeimage.posix.kt
test/graalvm/src/test/kotlin/GraalSmokeTest.kt

The issue with `Expected Object but got Word` when compiling the native image comes from the fact that the kotlin compiler insert null checks if the used types are not nullable.
For example, if we declare tcgetattr as
```kotlin
@CFunction("tcgetattr")
external fun tcgetattr(fd: Int, termios: termios): Int
```
Every call to it will be compiled as
```kotlin
Intrinsics.checkNotNull(termios);
tcgetattr(..., termios);
```
It is possible to disable those checks with the following compiler parameters:
-Xno-param-assertions, -Xno-call-assertions,-Xno-receiver-assertions.
But in this case, it is enough to simply mark the termios parameter as nullable.

Support raw mode for posix in native image

---

CHANGELOG.md
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.jvm.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/syscalls/nativeimage/SyscallHandler.nativeimage.linux.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/syscalls/nativeimage/SyscallHandler.nativeimage.macos.kt

This is a follow on to #186 that fixes the `termios` struct definition on macos.

Split out SyscallHandler.nativeimage.macos

---

CHANGELOG.md
mordant/src/appleMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.apple.kt
mordant/src/appleMain/kotlin/internal/syscalls/SyscallHanlder.native.apple.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/syscalls/jna/SyscallHandler.jna.linux.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/syscalls/jna/SyscallHandler.jna.macos.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/syscalls/nativeimage/SyscallHandler.nativeimage.linux.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/syscalls/nativeimage/SyscallHandler.nativeimage.macos.kt
mordant/src/linuxMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.linux.kt
mordant/src/linuxMain/kotlin/com/github/ajalt/mordant/internal/syscalls/SyscallHanlder.native.linux.kt
mordant/src/nativeMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.native.kt
mordant/src/nonJsMain/kotlin/com/github/ajalt/mordant/input/InteractiveSelectList.kt
mordant/src/nonJsMain/kotlin/com/github/ajalt/mordant/internal/syscalls/SyscallHandler.posix.kt
mordant/src/posixMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.posix.kt
mordant/src/posixMain/kotlin/com/github/ajalt/mordant/internal/syscalls/SyscallHanlder.native.posix.kt
mordant/src/posixMain/kotlin/com/github/ajalt/mordant/internal/tty.kt

Use platform-specific values for termios constants

---

mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/syscalls/nativeimage/SyscallHandler.nativeimage.linux.kt

When compiling a native image for linux with musl libc, the following error was displayed:
`'struct termios' has no member named 'c_ispeed'`
On musl, it is named `__c_ispeed`
Since we don't really need those fields anyway,
we can remove them from the struct definition.
We then need to mark the struct definition as incomplete. The documentation says:
If marked as incomplete, we will not try to determine the size of the struct.
`StackValue.get(structType)` is actually a shortcut for `StackValue.get(SizeOf.get(structType))`
We now simply need to pass the explicit size in bytes.
Fixes https://github.com/ajalt/mordant/issues/189

Prevent error with musl libc and GraalVM native image

---

mordant-jvm-ffm/api/mordant-jvm-ffm.api
mordant-jvm-ffm/build.gradle.kts
mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/TerminalInterfaceProvider.ffm.kt
mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/FfmLayouts.kt
mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/TerminalInterface.ffm.linux.kt
mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/TerminalInterface.ffm.macos.kt
mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/TerminalInterface.ffm.windows.kt
mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/TerminalInterfaceProvider.ffm.kt
mordant-jvm-ffm/src/jvmMain/resources/META-INF/native-image/com.github.ajalt.mordant/mordant-jvm-ffm/native-image.properties
mordant-jvm-ffm/src/jvmMain/resources/META-INF/services/com.github.ajalt.mordant.terminal.TerminalInterfaceProvider
mordant-jvm-graal-ffi/api/mordant-jvm-graal-ffi.api
mordant-jvm-graal-ffi/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/TerminalInterfaceProvider.nativeimage.kt
mordant-jvm-graal-ffi/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/nativeimage/TerminalInterface.nativeimage.linux.kt
mordant-jvm-graal-ffi/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/nativeimage/TerminalInterface.nativeimage.macos.kt
mordant-jvm-graal-ffi/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/nativeimage/TerminalInterface.nativeimage.windows.kt
mordant-jvm-graal-ffi/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/nativeimage/TerminalInterfaceProvider.nativeimage.kt
mordant-jvm-graal-ffi/src/jvmMain/resources/META-INF/native-image/com.github.ajalt.mordant/mordant-jvm-graal-ffi/native-image.properties
mordant-jvm-graal-ffi/src/jvmMain/resources/META-INF/services/com.github.ajalt.mordant.terminal.TerminalInterfaceProvider
mordant-jvm-jna/api/mordant-jvm-jna.api
mordant-jvm-jna/build.gradle.kts
mordant-jvm-jna/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/TerminalInterfaceProvider.jna.kt
mordant-jvm-jna/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/jna/TerminalInterface.jna.linux.kt
mordant-jvm-jna/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/jna/TerminalInterface.jna.macos.kt
mordant-jvm-jna/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/jna/TerminalInterface.jna.windows.kt
mordant-jvm-jna/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/jna/TerminalInterfaceProvider.jna.kt
mordant-jvm-jna/src/jvmMain/resources/META-INF/native-image/com.github.ajalt.mordant/mordant-jvm-jna/native-image.properties
mordant-jvm-jna/src/jvmMain/resources/META-INF/services/com.github.ajalt.mordant.terminal.TerminalInterfaceProvider
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.jvm.kt
mordant/src/jvmMain/resources/com.github.ajalt.mordant/mordant-core/native-image.properties
test/graalvm/src/test/kotlin/GraalSmokeTest.kt

This should solve GraalVM native image issues. See commits for details.
I tried the select sample and a personal project locally on linux X64 using
- native image 22.0.2-graal
- native image 21.0.4-graal
- JVM 21.0.4-graal
- JVM 22.0.2-graal
- JVM 17.0.10-tem
- JVM 11.0.22-tem
- JVM 8.0.402-tem
With Java 8, it fails
```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.Class.getModule()Ljava/lang/Module;
at com.github.ajalt.mordant.terminal.terminalinterface.ffm.TerminalInterfaceProviderFfm.load(TerminalInterfaceProvider.ffm.kt:10)
at com.github.ajalt.mordant.internal.MppInternal_jvmKt.getStandardTerminalInterface(MppInternal.jvm.kt:139)
at com.github.ajalt.mordant.internal.MppInternalKt.<clinit>(MppInternal.kt:60)
at …
```

Fix native image support

---

mordant-jvm-graal-ffi/build.gradle.kts
mordant-jvm-graal-ffi/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/nativeimage/TerminalInterface.nativeimage.windows.kt

I tried to use @RawFieldStructure to define the different union subtypes, but for some reasons, the offsets were not properly computed. This goal was to use pointer.readWord<KeyEventRecord>().
We can check the offsets using @RawFieldOffset.
For example this was the definition of KeyEventRecord
```kotlin
@RawStructure
interface KeyEventRecord extends PointerBase {
@RawField
void setBKeyDown(boolean value);
@RawField
boolean getBKeyDown();
@RawFieldOffset
static int offsetOfBKeyDown() {
return -1;
}
@RawField
void setWRepeatCount(short value);
@RawField
short getWRepeatCount();
@RawFieldOffset
static int offsetOfWRepeatCount() {
return -1;
}
@RawField
void setWVirtualKeyCode(short value);
@RawField
short getWVirtualKeyCode();
@RawFieldOffset
static int offsetOfWVirtualKeyCode() {
return -1; …
```

Use raw pointers for graal union struct

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/animation/progress/MultiProgressBarAnimation.kt

Keeping track of progress history was taking a lot of CPU load if updates were happening very frequently. 
@aSemy suggested an improvement in https://github.com/ajalt/mordant/issues/204#issuecomment-2295274887, and this PR goes further:
Instead of keeping a list with an entry for each call to `update`, we instead keep a fixed size list, and overwrite the last entry if it was very recent. We only look at the first and last entries to calculate speed, so there's no need to keep every entry.
```
Benchmark                        Mode  Cnt      Score      Error  Units
JmhBenchmark.benchmarkCurrent    avgt    3  34931.106 ± 1299.242  ns/op
JmhBenchmark.benchmarkAsemy      avgt    3   5474.108 ±  634.242  ns/op
JmhBenchmark.benchmarkFixedList  avgt    3    176.047 ±   53.293  ns/op
```
This …

Improve performance of progress bars under high concurrency

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/VerticalLayout.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/widgets/Caption.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/table/TableTest.kt

Fixes #216 
The issue was actually too much _horizontal_ space, which the terminal app hard wraps.

Fix whitespace of aligned table captions on narrow terminals

---

buildSrc/src/main/kotlin/mordant-js-conventions.gradle.kts
buildSrc/src/main/kotlin/mordant-mpp-conventions.gradle.kts
buildSrc/src/main/kotlin/mordant-native-conventions.gradle.kts
buildSrc/src/main/kotlin/mordant-native-core-conventions.gradle.kts
mordant-coroutines/build.gradle.kts
mordant-omnibus/build.gradle.kts
mordant-omnibus/src/commonMain/kotlin/com/github/ajalt/mordant/internal/OmibusInternal.kt
mordant/build.gradle.kts
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.jvm.kt

Make mordant-omnibus publish on all MPP targets

---

mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/FfmLayouts.kt
mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/TerminalInterface.ffm.linux.kt
mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/TerminalInterface.ffm.macos.kt

Specify variadic arguments for ffm ioctl call

---

mordant/src/commonMain/kotlin/com/github/ajalt/mordant/animation/progress/MultiProgressBarAnimation.kt

This PR fixes an issue where startTime was incorrectly set to pauseTime, ensuring accurate task progress tracking and speed estimation.
Updated:
```kotlin
val startTime = status.pauseTime ?: now
```
to: 
```kotlin
val startTime = status.startTime ?: now
```

fix(MultiProgressBarAnimation.kt): startTime

---

mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.jvm.kt

IDEA's debugger supports colors, but the terminal auto-detect only looks for the runtime(?) agent, named `idea_rt.jar`. A different agent is used for debugging, namely `debugger-agent.jar`. I added this to Intellij JVM arg detection code.

ft: support IDEA's debugger agent
