ajalt/mordant

mordant/src/main/kotlin/com/github/ajalt/mordant/TerminalCapabilities.kt

This PR adds support to turn colors on for rxvt terminal.
Thanks for this nice library btw!

Auto-detect rxvt terminal

---

mordant/src/commonMain/kotlin/com/github/ajalt/mordant/markdown/MarkdownRenderer.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/TableDsl.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/TableLayout.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/widgets/DefinitionList.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/widgets/Text.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/rendering/TextOverflowWrapTest.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/rendering/components/DefinitionListTest.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/rendering/components/TextTest.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/rendering/table/TableColumnWidthTest.kt

This addresses some of the comments from #13

Make default whitesapce PRE, add `whitespace` to table styles

---

README.md

It appears there were some changes in `Cursor` and `CursorMovement` as moving forward to v2.0. I'd like to update the documentation accordingly.

Update README ('Controlling the cursor' section)

---

mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/animation/ProgressAnimation.kt

Ticker can run whilst progress bar is being stopped:
```
Exception in thread "Timer-1" java.util.ConcurrentModificationException
at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
at com.github.ajalt.mordant.internal.MppImplKt.sendInterceptedPrintRequest(MppImpl.kt:142)
at com.github.ajalt.mordant.terminal.Terminal.sendPrintRequest(Terminal.kt:262)
at com.github.ajalt.mordant.terminal.Terminal.rawPrint(Terminal.kt:258)
at com.github.ajalt.mordant.terminal.Terminal.print(Terminal.kt:194)
at com.github.ajalt.mordant.animation.Animation.update(Animation.kt:65)
at com.github.ajalt.mordant.animation.ProgressAnimation$start$$inlined$synchronized$lambda$1.invoke(ProgressAnimation.kt:141)
at …
```

Fix race between ProgressAnimation ticker and user.

---

mordant/src/mingwX64Main/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt

Fix terminal size detection in windows

---

CHANGELOG.md
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/markdown/MarkdownRenderer.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/markdown/MarkdownTest.kt

Fix markdown parsing of tables with empty cells

---

mordant/src/commonMain/kotlin/com/github/ajalt/mordant/markdown/MarkdownRenderer.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/markdown/MarkdownTest.kt

Add rendering for short and full reference links. 
Add small tweak for tests

[#29]: add rendering for image with reference links

---

mordant/src/commonMain/kotlin/com/github/ajalt/mordant/markdown/MarkdownRenderer.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/markdown/MarkdownTest.kt

Pass through tildes in markdown

---

mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt

Fix exception in jvm shutdown hook

---

README.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/internal/AnsiRender.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/rendering/TextColors.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalColors.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/terminal/TerminalColorsTest.kt

Change TextColor parameter range to match colormath

---

mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/animation/Animation.kt
mordant/src/jvmTest/kotlin/com/github/ajalt/mordant/animation/ProgressAnimationTest.kt

Don't clear screen during animations unless necessary

---

mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/animation/Animation.kt

Fix a couple of regressions related to the clearing optimizations and add kdocs.

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/internal/MppH.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/Terminal.kt
mordant/src/jsMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt
mordant/src/nativeMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt

Syncronize interceptor mutation on JVM

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalDetection.kt

Fix terminal detection false positive for IntelliJ

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/internal/Parsing.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/markdown/MarkdownRenderer.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/widgets/TextTest.kt

Don't strip trailing line breaks from text

---

mkdocs.yml

Adds a light/dark mode toggle (which should be based on browser preference)
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle

docs - add light/dark mode toggle

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalDetection.kt

Detect JediTerm terminal

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/widgets/ProgressBar.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/widgets/ProgressBarTest.kt

Handle ProgressBar when width == 1

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalInfo.kt

Include output in interactive check

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/animation/Animation.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/StdoutTerminalInterface.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/Terminal.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalCursor.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/animation/AnimationTest.kt

Add Animation.stop

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/Borders.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/table/TableBorderTest.kt
samples/table/src/commonMain/kotlin/com/github/ajalt/mordant/samples/main.kt

Fix typo in Borders enum

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/animation/Animation.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/animation/AnimationTest.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/animation/ProgressAnimation.kt

Fix animation.stop on IntelliJ

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/animation/Animation.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/internal/MppH.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/animation/AnimationTest.kt
mordant/src/jsMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt
mordant/src/nativeMain/kotlin/com/github/ajalt/mordant/internal/MppImpl.kt

Fix animation size calculation and JNA exceptions

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalDetection.kt

Check Xterm version when TERM=xterm

---

mordant/src/jvmMain/resources/META-INF/proguard/mordant.pro

Integrate ProGuard rules in jvm lib

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/widgets/ProgressLayout.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/widgets/ProgressLayoutTest.kt

Add showPulse parameter to progressBar

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/Table.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/TableDsl.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/TableLayout.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/VerticalLayout.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/table/TableColumnWidthTest.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/widgets/TextTest.kt

Add ColumnWidth.Custom

---

mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalInfo.kt

Clarify docs on updateTerminalSize

---

docs/guide.md

Nothing major, but did cause some confusion when i was reading through the docs 🙂 
Thanks for the great library ❤️

Fix readme link in guide.md

---

docs/progress.md

Add missing animateOnCoroutine link to API docs in `progress.md`

---

.github/workflows/build.yml
.github/workflows/release.yml
buildSrc/src/main/kotlin/mordant-publishing-conventions.gradle.kts

`gradle/actions/setup-gradle` wants you to call gradle in a separate step now.

Update deprecated workflow usage

---

CHANGELOG.md
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.jvm.kt

Fixes https://github.com/ajalt/clikt/issues/522

Catch all exceptions in `runningInIdeaJavaAgent`

---

CHANGELOG.md
gradle/wrapper/gradle-wrapper.properties
gradlew
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/markdown/MarkdownRenderer.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/markdown/MarkdownTest.kt

Handle math expressions in markdown renderer

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/animation/progress/ProgressBarAnimation.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/widgets/progress/CachedProgressBarDefinition.kt

Remove retry limit for update spinlock

---

mordant/src/nonJsMain/kotlin/com/github/ajalt/mordant/input/RawMode.kt

- Do not throw an exception for timeout only to coerce back to null. Instead produce null, and throw an exception if desired.
- Ensure timeout when reading only keys or only mouse is properly applied to the whole operation rather than for any event read while looping.

Improve raw event timeout behavior

---

CHANGELOG.md
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/internal/MppInternal.jvm.kt

Catch throwable instead of exception in runningInIdeaJavaAgent

---

mordant/api/mordant.api
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/internal/Utf8.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalInterface.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/PosixEventParser.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/TerminalInterface.posix.kt
mordant/src/jsCommonMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/TerminalInterface.jsCommon.kt
mordant/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/TerminalInterface.jvm.posix.kt
mordant/src/posixMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/TerminalInterface.native.posix.kt

Speed up raw mode readRawByte

---

CHANGELOG.md
mordant/api/mordant.api
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/Terminal.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalDetection.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/terminal/TerminalTest.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/test/RenderingTest.kt

Add nonInteractiveWidth override

---

CHANGELOG.md
docs/input.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/PosixEventParser.kt

In raw mode, return Escape immediately.

---

mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/TerminalInterface.ffm.macos.kt

Update TIOCGWINSZ constant for ffm on arm mac

---

CHANGELOG.md
mordant/api/mordant.api
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/Terminal.kt

Change rawPrint to take a CharSequence

---

CHANGELOG.md
mordant-jvm-ffm/src/jvmMain/kotlin/com/github/ajalt/mordant/terminal/terminalinterface/ffm/TerminalInterface.ffm.windows.kt
mordant/api/mordant.api
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/input/RawMode.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/terminal/TerminalInterface.kt

Fix readOrNull throwing on timeout

---

docs/input.md

https://ajalt.github.io/mordant/input/#raw-mode-details

Fix mkdocs admonition in `input.md`

---

CHANGELOG.md
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/table/Table.kt
mordant/src/commonMain/kotlin/com/github/ajalt/mordant/widgets/Padding.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/table/TableLayoutTest.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/table/TableTest.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/test/RenderingTest.kt
mordant/src/commonTest/kotlin/com/github/ajalt/mordant/test/TestUtils.kt

Fix table borders for colspan cells
